# Typus Models Configuration File
#
# Use the README file on the same folder as this file as a reference to
# customize this file to your needs.

Category:
  fields:
    list: name, posts_count
    form: name
    show: id, name, posts_count, created_at, updated_at
  actions:
    index:
    edit:
  order_by:
  relationships: posts
  filters:
  search:
  application: Blog
  description:

Post:
  fields:
    list: title, slug, active, published_at
    form: title, slug, body, excerpt, published_at, active
    show: id, title, slug, active, body, excerpt, published_at, created_at, updated_at
  actions:
    index:
    edit:
  order_by:
  relationships:
  filters:
  search:
  application: Blog
  description:

